export const CLOSE_SENTENCE = 'Cerrar';
export const SEARCH_CARD_PLACEHOLDER = 'Busca cualquier carta...';
export const SEARCH_LABEL = 'Buscar';
export const BACK_SENTENCE = 'Volver';
export const NO_MATCH_SENTENCE = 'No se han encontrado cartas...';
export const HELP_SENTENCE = 'Ayuda';
export const SETTINGS_SENTENCE = 'Configuración';
export const NO_CONTEXT = 'No Context';
export const MUSIC_ERROR = 'Error al cargar/reproducir la música.'